version: '3'

services:
  db:
    image: mysql:8
    container_name: db
    ports:
      - 13306:3306
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: app_root_pass
      #MYSQL_DATABASE: gogo
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
      TZ: 'Asia/Tokyo'

  app:
    links: 
      - db
    build: ./golang
    container_name: goapisample
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/github.com/wt-l00/goapisample
    command: sh ./start_app.sh

