CREATE DATABASE IF NOT EXISTS `gogo`;
USE `gogo`;

CREATE TABLE IF NOT EXISTS entries(
	`id` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(256) NOT NULL,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;